CREATE TABLE TIME_INTERVAL (
    TIME_INTERVAL_ID INT PRIMARY KEY,
    TIME_INTERVAL_YEAR INT,
    TIME_INTERVAL_MONTH INT,
    TIME_INTERVAL_DAY INT,
    TIME_INTERVAL_HOUR INT
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CUSTOMER_ADDRESS VARCHAR(100)
);

CREATE TABLE REGULATOR (
    REGULATOR_ID INT PRIMARY KEY,
    REGULATOR_NAME VARCHAR(100),
    REGULATOR_ADDRESS VARCHAR(100)
);

CREATE TABLE CETUSER (
    CETUSER_ID INT PRIMARY KEY,
    CETUSER_ROLE VARCHAR(50)
);

CREATE TABLE CETUSER_CUSTOMER (
    CETUSER_ID INT PRIMARY KEY FOREIGN KEY REFERENCES CETUSER(CETUSER_ID),
    CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE CETUSER_REGULATOR (
    CETUSER_ID INT PRIMARY KEY FOREIGN KEY REFERENCES CETUSER(CETUSER_ID),
    REGULATOR_ID INT FOREIGN KEY REFERENCES REGULATOR(REGULATOR_ID)
);

CREATE TABLE TERRITORY (
    TERRITORY_ID INT PRIMARY KEY,
    TERRITORY_ADDRESS VARCHAR(100)
);

CREATE TABLE PRICE (
    PRICE_ID INT PRIMARY KEY,
    TIME_INTERVAL_ID INT FOREIGN KEY REFERENCES TIME_INTERVAL(TIME_INTERVAL_ID),
    PRICE_CURRENCY VARCHAR(10),
    PRICE_AMOUNT INT,
    PRICE_PAYMENT_TERMS VARCHAR(100)
);

CREATE TABLE CATPRODUCT (
    CATPRODUCT_ID INT PRIMARY KEY,
    PRICE_ID INT FOREIGN KEY REFERENCES PRICE(PRICE_ID),
    CATPRODUCT_CATEGORY VARCHAR(50),
    CATPRODUCT_CATALYST_TECH CHAR,
    CATPRODUCT_PARTICULATE_FILTER CHAR,
    CATPRODUCT_REGENERATION_SYSTEM CHAR,
    CATPRODUCT_DESCRIPTION TEXT
);

CREATE TABLE EM_STANDARD (
    EM_STANDARD_ID INT PRIMARY KEY,
    REGULATOR_ID INT FOREIGN KEY REFERENCES REGULATOR(REGULATOR_ID),
    TERRITORY_ID INT FOREIGN KEY REFERENCES TERRITORY(TERRITORY_ID),
    CATPRODUCT_ID INT FOREIGN KEY REFERENCES CATPRODUCT(CATPRODUCT_ID),
    EMISSION_CARBON_DIOXIDE FLOAT,
    EMISSION_CARBON_MONOXIDE FLOAT,
    EMISSION_METHANE FLOAT,
    EMISSION_NITROUS_OXIDE FLOAT,
    EMISSION_OTHER_NITROGEN_OXIDES FLOAT,
    EMISSION_OTHER_HYDROCARBONS FLOAT,
    EMISSION_PARTICULATE_MATTER FLOAT,
    EMISSION_STANDARD_UNIT_OF_MEASUREMENT VARCHAR(50)
);

CREATE TABLE WORKSITE (
    WORKSITE_ID INT PRIMARY KEY,
    TERRITORY_ID INT FOREIGN KEY REFERENCES TERRITORY(TERRITORY_ID),
    CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
    WORKSITE_ADDRESS VARCHAR(100),
    WORKSITE_DESCRIPTION TEXT
);

CREATE TABLE MACHINE (
    MACHINE_ID INT PRIMARY KEY,
    CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
    CATPRODUCT_ID INT FOREIGN KEY REFERENCES CATPRODUCT(CATPRODUCT_ID),
    WORKSITE_ID INT FOREIGN KEY REFERENCES WORKSITE(WORKSITE_ID),
    TIME_INTERVAL_ID INT FOREIGN KEY REFERENCES TIME_INTERVAL(TIME_INTERVAL_ID),
    PRICE_ID INT FOREIGN KEY REFERENCES PRICE(PRICE_ID),
    MACHINE_SERVICE_LIFE INT,
    MACHINE_ENGINE_POWER INT
);

CREATE TABLE EMISSION_RECORD (
    EMISSION_ID INT PRIMARY KEY,
    MACHINE_ID INT FOREIGN KEY REFERENCES MACHINE(MACHINE_ID),
    CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
    WORKSITE_ID INT FOREIGN KEY REFERENCES WORKSITE(WORKSITE_ID),
    TIME_INTERVAL_ID INT FOREIGN KEY REFERENCES TIME_INTERVAL(TIME_INTERVAL_ID),
    EMISSION_CARBON_DIOXIDE FLOAT,
    EMISSION_CARBON_MONOXIDE FLOAT,
    EMISSION_METHANE FLOAT,
    EMISSION_NITROUS_OXIDE FLOAT,
    EMISSION_OTHER_NITROGEN_OXIDES FLOAT,
    EMISSION_OTHER_HYDROCARBONS FLOAT,
    EMISSION_PARTICULATE_MATTER FLOAT,
    EMISSION_FUEL_TYPE VARCHAR(50),
    EMISSION_FUEL_SPENT FLOAT,
    EMISSION_OPERATING_TIME FLOAT
);

CREATE TABLE REPORT (
    REPORT_ID INT PRIMARY KEY,
    CETUSER_ID INT FOREIGN KEY REFERENCES CETUSER(CETUSER_ID),
    TIME_INTERVAL_ID INT FOREIGN KEY REFERENCES TIME_INTERVAL(TIME_INTERVAL_ID),
    REPORT_TITLE VARCHAR(100),
    REPORT_QUERY TEXT,
    REPORT_OUTPUT TEXT
);
